# Generated by Django 5.1.3 on 2024-12-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
    ]
