# Generated by Django 5.1.3 on 2024-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('proficiency', models.ManyToManyField(related_name='aproficiency', to='home.skill')),
                ('skill', models.ManyToManyField(related_name='askill', to='home.skill')),
                ('number', models.ManyToManyField(related_name='anumber', to='home.info')),
                ('title', models.ManyToManyField(related_name='atitle', to='home.info')),
            ],
        ),
    ]
