# Generated by Django 5.1.3 on 2024-12-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_info_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='number',
        ),
        migrations.RemoveField(
            model_name='about',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
