# Generated by Django 5.1.3 on 2024-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_about_number_remove_about_proficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YourSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_percent', models.IntegerField(help_text='out of 100')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project', models.ManyToManyField(to='home.yourproject')),
                ('skill', models.ManyToManyField(to='home.yourskill')),
            ],
        ),
    ]
