# Generated by Django 5.1.3 on 2024-12-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/portfolio')),
                ('video_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/portfolio/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfo.portfoliodetail')),
            ],
        ),
    ]
