# Generated by Django 5.1.3 on 2024-12-14 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetail',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
