# Generated by Django 5.1.3 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0004_blogdetail_contentblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='portfo.category'),
        ),
    ]
